version: '3.8'
services:
  mysql_main:
    container_name: mysql_main
    hostname: mysql_main
    platform: ${MYSQL_PLATFORM}
    image: mysql/mysql-server:${MYSQL_SERVER_TAG}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_MAIN_DIR}/conf/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${MYSQL_MAIN_DIR}/conf/my.cnf:/etc/mysql/my.cnf
      - mysql-main-data-volume:/var/lib/mysql
    ports:
      - '${FORWARD_MAIN_MYSQL_PORT:-3306}:3306'

  mysql_replica:
    container_name: mysql_replica
    hostname: mysql_replica
    platform: ${MYSQL_PLATFORM}
    image: mysql/mysql-server:${MYSQL_SERVER_TAG}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql_main
    volumes:
      - ${MYSQL_REPLICA_DIR}/conf/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${MYSQL_REPLICA_DIR}/conf/my.cnf:/etc/mysql/my.cnf
      - mysql-replica-data-volume:/var/lib/mysql
    ports:
      - '${FORWARD_REPLICA_MYSQL_PORT:-3306}:3306'

volumes:
  mysql-main-data-volume:
  mysql-replica-data-volume: