spring:
  application:
    name: dynamic_data_source
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    #    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
  dynamic-data-source:
    jdbc-url-post-fix: "useSSL=false&useUnicode=true&characterEncoding=utf-8"
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      host: localhost
      main:
        host: ${spring.dynamic-data-source.mysql.host}
        url: jdbc:mysql://${spring.dynamic-data-source.mysql.main.host}:3306/${spring.application.name}?${spring.dynamic-data-source.jdbc-url-post-fix}
        username: root
        password: password
        driverClassName: ${spring.dynamic-data-source.mysql.driver-class-name}
      replica:
        host: ${spring.dynamic-data-source.mysql.host}
        url: jdbc:mysql://${spring.dynamic-data-source.mysql.replica.host}:3307/${spring.application.name}?${spring.dynamic-data-source.jdbc-url-post-fix}
        username: root
        password: password
        driverClassName: ${spring.dynamic-data-source.mysql.driver-class-name}
    postgresql:
      driver-class-name: org.postgresql.Driver
      host: localhost
      main:
        host: ${spring.dynamic-data-source.postgresql.host}
        url: jdbc:postgresql://${spring.dynamic-data-source.postgresql.main.host}:5432/${spring.application.name}?
        username: postgres
        password: password
        driverClassName: ${spring.dynamic-data-source.postgresql.driver-class-name}
      replica:
        host: ${spring.dynamic-data-source.postgresql.host}
        url: jdbc:postgresql://${spring.dynamic-data-source.postgresql.replica.host}:5433/${spring.application.name}?
        username: postgres
        password: password
        driverClassName: ${spring.dynamic-data-source.postgresql.driver-class-name}

server:
  port: 8081
