CREATE
DATABASE dynamic_data_source;
GRANT
SELECT, USAGE
ON ALL TABLES IN SCHEMA public TO postgres;
GRANT
EXECUTE
ON
ALL
FUNCTIONS IN SCHEMA public TO postgres;
GRANT
SELECT
ON ALL SEQUENCES IN SCHEMA public TO postgres;